using System;
using UnityEngine;
using UnityEngine.UI;
using static PlayerController;

public class ChangeMoveModeButton : MonoBehaviour
{
    [SerializeField]
    private Button _button;
    [SerializeField]
    private Text _label;
    [SerializeField]
    private PlayerController _playerController;

    private void Start()
    {
        UpdateLabel(_playerController.CurrentMoveMode);
        _playerController.OnMoveModeChanged += UpdateLabel;

        _button.onClick.AddListener(OnButtonClicked);
    }

    private void OnDestroy()
    {
        _playerController.OnMoveModeChanged -= UpdateLabel;

        _button.onClick.RemoveListener(OnButtonClicked);
    }

    private void UpdateLabel(MoveMode moveMode)
    {
        _label.text = $"Move Mode: {moveMode.ToString()}";
    }

    private void OnButtonClicked()
    {
        var currentMoveMode = _playerController.CurrentMoveMode;
        // Œ»چف‚جMoveMode‚ھƒ}ƒjƒ…ƒAƒ‹‚ب‚çƒIپ[ƒg‚ة‚·‚éپB
        if (currentMoveMode == MoveMode.Manual)
        {
            _playerController.BeginMoveCoroutine(MoveMode.Auto);
        }
        // Œ»چف‚جMoveMode‚ھƒIپ[ƒg‚©ƒ{ƒX‚ب‚çƒ}ƒjƒ…ƒAƒ‹‚ة‚·‚éپB
        else if (currentMoveMode == MoveMode.Auto || currentMoveMode == MoveMode.GoToBoss)
        {
            _playerController.BeginMoveCoroutine(MoveMode.Manual);
        }
        else
        {
            throw new ArgumentException("ˆع“®ƒ‚پ[ƒh‚ج•دچX‚ةژ¸”sپB");
        }
    }
}